"""
נוצר אוטומטית ע"י gen_tier_b_catalog.py מתוך src/config/fields.ts.
לא לערוך ידנית — להריץ את המחולל מחדש.
"""

# מפתח DB: (תווית בעברית, סוג המרה, קבוצה)
CATALOG: dict[str, tuple[str, str, str]] = {
    'MISPAR_ZEHUT': ('מספר זהות', 'id', 'פרטים אישיים'),
    'SHEM_MISHPACHA': ('שם משפחה', 'text', 'פרטים אישיים'),
    'SHEM_PRATI': ('שם פרטי', 'text', 'פרטים אישיים'),
    'CODE_MIN': ('מין', 'text', 'פרטים אישיים'),
    'TAARICH_LEDA': ('תאריך לידה', 'date', 'פרטים אישיים'),
    'SUG_ZEHUT': ('סוג זהות', 'text', 'פרטים אישיים'),
    'MISPAR_DARKON': ('מספר דרכון', 'text', 'פרטים אישיים'),
    'KVUTSAT_DARKON': ('קבוצת דרכון', 'text', 'פרטים אישיים'),
    'SHEM_MISHPACHA_KINUI': ('שם משפחה כינוי', 'text', 'פרטים אישיים'),
    'SHEM_PRATI_KINUI': ('שם פרטי כינוי', 'text', 'פרטים אישיים'),
    'CODE_LEOM_PNIM': ('לאום משרד הפנים', 'text', 'פרטים אישיים'),
    'CODE_ERETS_LEDA': ('שם ארץ לידה', 'text', 'פרטים אישיים'),
    'CODE_ERETS_ALIYA': ('שם ארץ עליה', 'text', 'פרטים אישיים'),
    'TAARICH_ALIYA': ('תאריך עליה', 'date', 'פרטים אישיים'),
    'MISPAR_ACHIM_AD_18': ('מספר אחים עד 18', 'number', 'פרטים אישיים'),
    'TAARICH_CHAZARA_MCHUL': ('תאריך חזרה מחול', 'date', 'פרטים אישיים'),
    'SHNOT_LIMUD_BCHUL': ('שנות לימוד בחול', 'number', 'פרטים אישיים'),
    'MISPAR_ZEHUT_KODEMET': ('מספר זהות קודם', 'id', 'פרטים אישיים'),
    'SUG_ZEHUT_KODEMET': ('סוג זהות קודמת', 'text', 'פרטים אישיים'),
    'TAARICH_IDKUN_RESHUMA': ('תאריך עדכון מקסימלי', 'date', 'פרטים אישיים'),
    'HAIM_PIRTEY_KESHER_TALMID': ('האם פרטי קשר תלמיד', 'text', 'פרטים אישיים'),
    'SEMEL_MOSAD': ('סמל מוסד', 'text', 'מוסד'),
    'SHEM_MOSAD': ('שם מוסד', 'text', 'מוסד'),
    'MUTAV': ('סמל מוטב', 'text', 'מוסד'),
    'RASHUT_CHINUCH_MOSAD': ('סמל רשות חינוך', 'text', 'מוסד'),
    'RASHUT_CHINUCH_TEUR': ('שם רשות חינוך', 'text', 'מוסד'),
    'SUG_MOSAD_TEUR': ('סוג מסגרת', 'text', 'מוסד'),
    'SHEM_YISHUV': ('ישוב מוסד', 'text', 'מוסד'),
    'KTOVET_MOSAD': ('כתובת מוסד', 'text', 'מוסד'),
    'TELEFON_MOSAD': ('טלפון מוסד', 'text', 'מוסד'),
    'GOREM_MEDAVEACH_TEUR': ('גורם מדווח תאור', 'text', 'מוסד'),
    'MIGZAR_TEUR': ('מגזר', 'text', 'מוסד'),
    'MAAMAD_MISHPATI_TEUR': ('מעמד משפטי תאור', 'text', 'מוסד'),
    'SUG_PIKUACH_TEUR': ('סוג פיקוח תאור', 'text', 'מוסד'),
    'SUG_CHINUCH_TEUR': ('סוג חינוך תאור', 'text', 'מוסד'),
    'SHLAV_HINUCH_TEUR': ('שלבי חינוך מוסד', 'text', 'מוסד'),
    'SHNAT_LIMUDIM': ('שנת לימודים', 'text', 'מוסד'),
    'SHICHVA': ('שכבה', 'text', 'כיתה ומגמה'),
    'MAKBILA': ('מקבילה', 'text', 'כיתה ומגמה'),
    'CODE_SUG_KITA': ('קוד סוג כיתה', 'text', 'כיתה ומגמה'),
    'TEUR_SUG_KITA': ('סוג כיתה', 'text', 'כיתה ומגמה'),
    'TEUR_STATUS_ISHUR': ('סטטוס אישור כיתה', 'text', 'כיתה ומגמה'),
    'TAARICH_STATUS_ISHUR_KITA': ('תאריך סטטוס אישור כיתה', 'date', 'כיתה ומגמה'),
    'MIN_TALMIDIM': ('מינימום תלמידים בכיתה', 'number', 'כיתה ומגמה'),
    'MAX_TALMIDIM': ('מקסימום תלמידים בכיתה', 'number', 'כיתה ומגמה'),
    'CODE_MASLUL': ('מסלול', 'text', 'כיתה ומגמה'),
    'CODE_NATIV': ('נתיב', 'text', 'כיתה ומגמה'),
    'CODE_HASMACHA': ('הסמכה', 'text', 'כיתה ומגמה'),
    'SEMEL_MEGAMA_MISRAD_x': ('סמל מגמה משרד', 'text', 'כיתה ומגמה'),
    'TEUR_MEGAMA_MISRAD': ('תאור מגמה משרד', 'text', 'כיתה ומגמה'),
    'SEMEL_MEGAMA_MOSAD': ('סמל מגמה מוסד', 'text', 'כיתה ומגמה'),
    'SHEM_MEGAMA_MOSAD': ('תאור מגמה מוסד', 'text', 'כיתה ומגמה'),
    'MICHSAT_TALMIDIM_MEVUKESHET': ('מכסת תלמידים מבוקשת', 'number', 'כיתה ומגמה'),
    'TEUR_STATUS_ISHUR_MEGAMA': ('סטטוס אישור מגמה', 'text', 'כיתה ומגמה'),
    'RASHUT_TALMID': ('סמל רשות מגורים תלמיד', 'text', 'שיבוץ וסטטוס'),
    'CODE_STATUS_RISHUM_TA': ('תקינות שיבוץ', 'text', 'שיבוץ וסטטוס'),
    'TKINUT_SHIBUTZ': ('תקינות שיבוץ (תאור)', 'text', 'שיבוץ וסטטוס'),
    'LO_LE_DIVUACH_MATZEVET': ('לא לדווח מצבת', 'text', 'שיבוץ וסטטוס'),
    'CODE_ZAKAUT_LSCHAR_LIMUD': ('קוד זכאות לשכר לימוד', 'text', 'שיבוץ וסטטוס'),
    'HAIM_RASHUT_ACHERET': ('האם רשות אחרת תאור', 'text', 'שיבוץ וסטטוס'),
    'TEUR_SIBAT_AZIVA': ('סיבת עזיבה', 'text', 'שיבוץ וסטטוס'),
    'PIRUT_AZIVA': ('פירוט עזיבה', 'text', 'שיבוץ וסטטוס'),
    'TAARICH_HATCHALA': ('תאריך תחילת שיבוץ', 'date', 'שיבוץ וסטטוס'),
    'TAARICH_SIYUM': ('תאריך סיום שיבוץ', 'date', 'שיבוץ וסטטוס'),
    'SEMEL_YISHUV1': ('סמל ישוב 1ת', 'locality', 'כתובת'),
    'TEUR_YISHUV1': ('תאור ישוב 1ת', 'text', 'כתובת'),
    'SHEM_RECHOV1': ('שם רחוב 1ת', 'text', 'כתובת'),
    'MISPAR_BAYIT1': ('מספר בית 1ת', 'text', 'כתובת'),
    'MISPAR_DIRA1': ('מספר דירה 1ת', 'text', 'כתובת'),
    'SEMEL_YESHUV2': ('סמל ישוב 2ת', 'locality', 'כתובת'),
    'TEUR_YESHUV2': ('תאור ישוב 2ת', 'text', 'כתובת'),
    'SHEM_RECHOV2': ('שם רחוב 2ת', 'text', 'כתובת'),
    'MISPAR_BAIT2': ('מספר בית 2ת', 'text', 'כתובת'),
    'KNISA2': ('כניסה 2ת', 'text', 'כתובת'),
    'MISPAR_DIRA2': ('מספר דירה 2ת', 'text', 'כתובת'),
    'TA_DOAR2': ('תא דואר 2ת', 'text', 'כתובת'),
    'MIKUD2': ('מיקוד 2ת', 'text', 'כתובת'),
    'SHCHUNA2': ('שכונה 2ת', 'text', 'כתובת'),
    'HEARA2': ('הערה 2ת', 'text', 'כתובת'),
    'DOAR_NA2': ('דואר נע 2ת', 'text', 'כתובת'),
    'GOREM_KESHER_1_ID': ('ת.ז. הורה 1', 'id', 'הורים'),
    'GOREM_KESHER_1_FULL_NAME': ('שם הורה 1', 'text', 'הורים'),
    'GOREM_KESHER_1_CODE_MAAMAD_HORE': ('מעמד הורה 1', 'text', 'הורים'),
    'GOREM_KESHER_1_CODE_SUG_KIRVA': ('קרבה הורה 1', 'text', 'הורים'),
    'GOREM_KESHER_1_SUG_ZEHUT': ('סוג זהות הורה 1', 'text', 'הורים'),
    'GOREM_KESHER_1_LEKABEL_MEIDA': ('האם לקבל מידע 1', 'text', 'הורים'),
    'GOREM_KESHER_1_HAIM_MESHALEM': ('האם משלם 1', 'text', 'הורים'),
    'EMAIL_parent1': ('מייל הורה 1', 'email', 'הורים'),
    'TEUR_YISHUV1_parent1': ('ישוב הורה 1', 'text', 'הורים'),
    'SHEM_RECHOV1_parent1': ('רחוב הורה 1', 'text', 'הורים'),
    'MISPAR_BAYIT1_parent1': ('מספר בית הורה 1', 'text', 'הורים'),
    'MISPAR_DIRA1_parent1': ('מספר דירה הורה 1', 'text', 'הורים'),
    'MIKUD7_parent1': ('מיקוד הורה 1', 'text', 'הורים'),
    'HAIM_PIRTEY_KESHER_TALMID_parent1': ('האם פרטי קשר תלמיד (הורה 1)', 'text', 'הורים'),
    'GOREM_KESHER_2_ID': ('ת.ז. הורה 2', 'id', 'הורים'),
    'GOREM_KESHER_2_FULL_NAME': ('שם הורה 2', 'text', 'הורים'),
    'GOREM_KESHER_2_CODE_MAAMAD_HORE': ('מעמד הורה 2', 'text', 'הורים'),
    'GOREM_KESHER_2_CODE_SUG_KIRVA': ('קרבה הורה 2', 'text', 'הורים'),
    'GOREM_KESHER_2_SUG_ZEHUT': ('סוג זהות הורה 2', 'text', 'הורים'),
    'GOREM_KESHER_2_LEKABEL_MEIDA': ('האם לקבל מידע 2', 'text', 'הורים'),
    'GOREM_KESHER_2_HAIM_MESHALEM': ('האם משלם 2', 'text', 'הורים'),
    'TEUR_YESHUV2_parent2': ('ישוב הורה 2', 'text', 'הורים'),
    'SHEM_RECHOV2_parent2': ('רחוב הורה 2', 'text', 'הורים'),
    'MISPAR_BAIT2_parent2': ('מספר בית הורה 2', 'text', 'הורים'),
    'MISPAR_DIRA2_parent2': ('מספר דירה הורה 2', 'text', 'הורים'),
    'MIKUD7_parent2': ('מיקוד מרשם הורה 2', 'text', 'הורים'),
    'MIKUD2_parent2': ('מיקוד הורה 2', 'text', 'הורים'),
    'SHCHUNA2_parent2': ('שכונה הורה 2', 'text', 'הורים'),
    'KNISA2_parent2': ('כניסה הורה 2', 'text', 'הורים'),
    'TA_DOAR2_parent2': ('תא דואר הורה 2', 'text', 'הורים'),
    'HEARA2_parent2': ('הערה הורה 2', 'text', 'הורים'),
    'DOAR_NA2_parent2': ('דואר נע הורה 2', 'text', 'הורים'),
    'MATZAV_RISHUM_CODE': ('קוד מצב רישום', 'text', 'שיבוץ וסטטוס'),
    'NAYAD_1_talmid': ('נייד 1 תלמיד', 'phone', 'פרטים אישיים'),
    'NAYAD_2_talmid': ('נייד 2 תלמיד', 'phone', 'פרטים אישיים'),
    'NAYACH_1_talmid': ('נייח 1 תלמיד', 'phone', 'פרטים אישיים'),
    'NAYACH_2_talmid': ('נייח 2 תלמיד', 'phone', 'פרטים אישיים'),
    'EMAIL_talmid': ('מייל תלמיד', 'email', 'פרטים אישיים'),
    'NAYAD_1_parent1': ('נייד 1 הורה 1', 'phone', 'הורים'),
    'NAYAD_2_parent1': ('נייד 2 הורה 1', 'phone', 'הורים'),
    'NAYACH_1_parent1': ('נייח 1 הורה 1', 'phone', 'הורים'),
    'NAYACH_2_parent1': ('נייח 2 הורה 1', 'phone', 'הורים'),
    'NAYAD_1_parent2': ('נייד 1 הורה 2', 'phone', 'הורים'),
    'NAYAD_2_parent2': ('נייד 2 הורה 2', 'phone', 'הורים'),
    'NAYACH_1_parent2': ('נייח 1 הורה 2', 'phone', 'הורים'),
    'NAYACH_2_parent2': ('נייח 2 הורה 2', 'phone', 'הורים'),
    'EMAIL_parent2': ('מייל הורה 2', 'email', 'הורים'),
    'YISHUV_MIRSHAM_parent1': ('ישוב מרשם הורה 1', 'text', 'הורים'),
    'RECHOV_MIRSHAM_parent1': ('רחוב מרשם הורה 1', 'text', 'הורים'),
    'MISPAR_BAYIT_MIRSHAM_parent1': ('מספר בית מרשם הורה 1', 'text', 'הורים'),
    'YISHUV_MIRSHAM_parent2': ('ישוב מרשם הורה 2', 'text', 'הורים'),
    'RECHOV_MIRSHAM_parent2': ('רחוב מרשם הורה 2', 'text', 'הורים'),
    'MISPAR_BAYIT_MIRSHAM_parent2': ('מספר בית מרשם הורה 2', 'text', 'הורים'),
    'SHEM_RASHUT_MEGURIM_TALMID': ('שם רשות מגורים תלמיד', 'text', 'כתובת'),
    'SHEM_MUTAV': ('שם מוטב', 'text', 'מוסד'),
    'TEUR_ZAKAUT_LSCHAR_LIMUD': ('זכאות לשכר לימוד', 'text', 'שיבוץ וסטטוס'),
    'HAIM_LESHIBUTZ_TEUR': ('האם לשיבוץ', 'text', 'שיבוץ וסטטוס'),
}
